version: '3.8'

services:
  app-dev:
    container_name: bots-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - app_logs:/app/logs
    depends_on:
      - db  
    networks:
      - app-network

  front:
    container_name: bots-front-dev
    build:
      context: ../front-bot
      dockerfile: Dockerfile.dev
    env_file:
      - ../front-bot/.env.front
    ports:
      - "4200:4200"
    volumes:
      - ../front-bot:/app
      - /app/node_modules
    depends_on:
      - app-dev
    networks:
      - app-network

  db: 
    image: postgres:17-alpine
    container_name: bots-api-db
    env_file:
      - .env.db
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db-data:
  app_logs:
