import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1750603433249 implements MigrationInterface {
    name = 'InitialSchema1750603433249'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Campuses" ("uuid_campus" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "uuid_guild" character varying(19) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uuid_role" character varying NOT NULL, CONSTRAINT "REL_82ea80834d8802c2f30e992425" UNIQUE ("uuid_role"), CONSTRAINT "PK_e1ae8d6a84f77e2ffb379fa9afd" PRIMARY KEY ("uuid_campus"))`);
        await queryRunner.query(`CREATE TABLE "Channels" ("uuid_channel" character varying(19) NOT NULL, "name" character varying(100) NOT NULL, "type" character varying(20) NOT NULL, "channel_position" integer NOT NULL, "uuid_category" character varying(19), "uuid_guild" character varying(19) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02bb2516002618a23bc5da17390" PRIMARY KEY ("uuid_channel"))`);
        await queryRunner.query(`CREATE TABLE "guilds_templates" ("uuid_guild_template" character varying(19) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "uuidGuild" character varying(19), "configuration" jsonb DEFAULT '{"channels":[],"roles":[],"permissions":{}}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "uuid_category" character varying(19), CONSTRAINT "REL_f67fd100e0c22aa439a6c33b4e" UNIQUE ("uuidGuild"), CONSTRAINT "REL_5be5909b1bba191edc06f7c0ed" UNIQUE ("uuid_category"), CONSTRAINT "PK_5c6eceaf8773ca29bd93bf95d18" PRIMARY KEY ("uuid_guild_template"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("uuid_category" character varying(36) NOT NULL, "name" character varying(50) NOT NULL, "position" integer NOT NULL, "uuidGuild" character varying(19) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uuid_guild_template" character varying(19), CONSTRAINT "REL_2580e5895d8ab1586560274598" UNIQUE ("uuid_guild_template"), CONSTRAINT "PK_f73f4f4a7ab89f40682b89cc0c4" PRIMARY KEY ("uuid_category"))`);
        await queryRunner.query(`CREATE TABLE "thread_template" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "forumId" character varying NOT NULL, "threadPosition" integer NOT NULL DEFAULT '0', "formationUuidFormation" uuid NOT NULL, CONSTRAINT "PK_a51ab4ae6974443c6802c2da03e" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "formation" ("uuidFormation" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "uuidGuild" character varying NOT NULL, "uuidRole" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "categoryUuid" character varying(36), "guildUuid" character varying(19), CONSTRAINT "PK_73a36e9394824d694a7e8685f96" PRIMARY KEY ("uuidFormation"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("uuid_role" character varying NOT NULL, "name" character varying(50) NOT NULL, "memberCount" integer NOT NULL, "rolePosition" integer NOT NULL, "hoist" boolean NOT NULL DEFAULT false, "color" character varying(7) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uuid_guild" character varying NOT NULL, CONSTRAINT "PK_f9ce0918e67ec465952fec03f3a" PRIMARY KEY ("uuid_role"))`);
        await queryRunner.query(`CREATE TABLE "Promotions" ("uuid_promotion" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "uuid_formation" uuid NOT NULL, "uuid_guild" character varying(19), "uuid_role" character varying(19), "uuid_campus" uuid NOT NULL, "uuid_category" character varying(19), CONSTRAINT "REL_dd8a497450643cd57b320413f6" UNIQUE ("uuid_role"), CONSTRAINT "REL_7f4379f872ac6471a39ed97a92" UNIQUE ("uuid_category"), CONSTRAINT "PK_94255bd6a8651548068fd7e19b9" PRIMARY KEY ("uuid_promotion"))`);
        await queryRunner.query(`CREATE TABLE "guilds" ("uuid_guild" character varying(19) NOT NULL, "name" character varying(50) NOT NULL, "member_count" character varying(50) NOT NULL, "configuration" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d7504192a3b6f24b6b8ac184cc4" PRIMARY KEY ("uuid_guild"))`);
        await queryRunner.query(`CREATE TABLE "members_informations" ("uuid_members_infos" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstname" character varying(50) NOT NULL, "lastname" character varying(50) NOT NULL, "email" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "uuidMember" uuid, CONSTRAINT "REL_c9c5d035e2236c8fc31b923e9c" UNIQUE ("uuidMember"), CONSTRAINT "PK_9e0cf869b09790f209f2d486e63" PRIMARY KEY ("uuid_members_infos"))`);
        await queryRunner.query(`CREATE TABLE "identification_requests" ("uuid_identification_request" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstname" character varying(50) NOT NULL, "lastname" character varying(50) NOT NULL, "email" character varying(50) NOT NULL, "uuidMember" uuid NOT NULL, CONSTRAINT "REL_199fe5af8e036ffedd4e8b39aa" UNIQUE ("uuidMember"), CONSTRAINT "PK_dde9202ac02731d4eb6f3d3b1e2" PRIMARY KEY ("uuid_identification_request"))`);
        await queryRunner.query(`CREATE TABLE "dashboard_accounts" ("uuid_dashboard_account" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, "uuid_discord" uuid NOT NULL, "uuidDiscord" character varying(19), CONSTRAINT "UQ_4ebd235b9c6888854cd660b97f2" UNIQUE ("email"), CONSTRAINT "REL_e846d03e8221a331dbbb27e4ff" UNIQUE ("uuidDiscord"), CONSTRAINT "PK_efe9878bd2693283e459d983ab5" PRIMARY KEY ("uuid_dashboard_account"))`);
        await queryRunner.query(`CREATE TABLE "discord_users" ("uuid_discord" character varying(19) NOT NULL, "discord_username" character varying(50) NOT NULL, "discriminator" character varying(50) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "avatar" character varying(255), CONSTRAINT "PK_3b58e48b1fa27fd897e4934bd69" PRIMARY KEY ("uuid_discord"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('resource', 'member')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_category_enum" AS ENUM('spam', 'harassment', 'inappropriate', 'other')`);
        await queryRunner.query(`CREATE TABLE "reports" ("uuid_report" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."reports_type_enum" NOT NULL, "category" "public"."reports_category_enum" NOT NULL, "reason" character varying(50) NOT NULL, "status" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "reporter_uuid" uuid, "resource_uuid" uuid, "reported_member_uuid" uuid, CONSTRAINT "UQ_a31d6d178038f2975b15d70565d" UNIQUE ("reporter_uuid", "resource_uuid", "reported_member_uuid"), CONSTRAINT "PK_fd462f6091de8938d1940ceca2f" PRIMARY KEY ("uuid_report"))`);
        await queryRunner.query(`CREATE TYPE "public"."votes_type_enum" AS ENUM('upvote', 'downvote')`);
        await queryRunner.query(`CREATE TABLE "votes" ("uuid_vote" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."votes_type_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uuid_member" uuid, "uuid_resource" uuid, "uuid_comment" uuid, CONSTRAINT "UQ_6ced81b3716bc9e48a6b803c4fd" UNIQUE ("uuid_member", "uuid_comment"), CONSTRAINT "UQ_1a5a91f748a964e990cbc42d9b9" UNIQUE ("uuid_member", "uuid_resource"), CONSTRAINT "PK_bbe5e384ef2b55fd34de6c91f7e" PRIMARY KEY ("uuid_vote"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("uuid_comment" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "status" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "uuid_member" uuid NOT NULL, "uuid_resource" uuid NOT NULL, CONSTRAINT "PK_66b8b2112dd89f2539f8b0f68e5" PRIMARY KEY ("uuid_comment"))`);
        await queryRunner.query(`CREATE TYPE "public"."resources_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "resources" ("uuid_resource" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "description" text NOT NULL, "content" text NOT NULL, "status" "public"."resources_status_enum" NOT NULL, "creator_uuid" uuid NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6c03d718865f3ede09aafba2a6c" PRIMARY KEY ("uuid_resource"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("uuid_answer" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying(50) NOT NULL, "uuid_question" uuid, CONSTRAINT "PK_3111ea4d8f54e1734346a58a561" PRIMARY KEY ("uuid_answer"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("uuid_question" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "is_multiple_answer" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "uuid_poll" uuid, CONSTRAINT "PK_4e1265304c53118c5275ec52c4c" PRIMARY KEY ("uuid_question"))`);
        await queryRunner.query(`CREATE TABLE "polls" ("uuid_poll" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "uuid_message" character varying(19) NOT NULL, "is_anonymous" boolean NOT NULL, "is_closed" boolean NOT NULL, "duration" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "uuid_author" uuid NOT NULL, CONSTRAINT "PK_b93ca80681aa25fd15702ba5289" PRIMARY KEY ("uuid_poll"))`);
        await queryRunner.query(`CREATE TABLE "members" ("uuid_member" uuid NOT NULL DEFAULT uuid_generate_v4(), "guild_username" character varying(50) NOT NULL, "xp" numeric(15,2) NOT NULL, "level" integer NOT NULL, "community_role" character varying(50) NOT NULL, "status" character varying(50) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uuid_guild" character varying NOT NULL, "uuid_discord" character varying NOT NULL, CONSTRAINT "PK_1d65310da00443918c38c3c24ca" PRIMARY KEY ("uuid_member"))`);
        await queryRunner.query(`CREATE TYPE "public"."xp_transactions_transaction_type_enum" AS ENUM('GAIN', 'LOSS')`);
        await queryRunner.query(`CREATE TYPE "public"."xp_transactions_source_enum" AS ENUM('VOTE', 'DOWNVOTE', 'RESOURCE_CREATION', 'RESOURCE_DELETION', 'REPORT', 'MANUAL', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."xp_transactions_reference_type_enum" AS ENUM('resource', 'vote', 'report', 'comment', 'answer', 'poll', 'poll_vote')`);
        await queryRunner.query(`CREATE TABLE "xp_transactions" ("uuid_xp_transaction" uuid NOT NULL DEFAULT uuid_generate_v4(), "transaction_type" "public"."xp_transactions_transaction_type_enum" NOT NULL, "source" "public"."xp_transactions_source_enum" NOT NULL, "transaction_value" numeric(15,2) NOT NULL, "reason" character varying(200) NOT NULL, "notes" character varying(500), "reference_type" "public"."xp_transactions_reference_type_enum", "reference_uuid" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "uuid_member" uuid, CONSTRAINT "PK_afd210a177c7ccad9b6cdd60c65" PRIMARY KEY ("uuid_xp_transaction"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "PK_46eb0c89341869ba6c882edab36" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "poll-templates" ("uuid_poll_template" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "is_anonymous" boolean NOT NULL, "duration" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), CONSTRAINT "PK_b3c837e2ac815f5d7d81297f0d5" PRIMARY KEY ("uuid_poll_template"))`);
        await queryRunner.query(`CREATE TABLE "answer-templates" ("uuid_answer_template" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying(50) NOT NULL, "uuid_question_template" uuid, CONSTRAINT "PK_1692b75702937faaf89a4acb3d9" PRIMARY KEY ("uuid_answer_template"))`);
        await queryRunner.query(`CREATE TABLE "question-templates" ("uuid_question_template" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "is_multiple_answer" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "uuid_poll_template" uuid, CONSTRAINT "PK_ece2c06de82c39fcc60da8fc45b" PRIMARY KEY ("uuid_question_template"))`);
        await queryRunner.query(`CREATE TYPE "public"."moderator_actions_action_type_enum" AS ENUM('warning', 'ban', 'content_removal', 'resolved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "moderator_actions" ("uuid_moderation" uuid NOT NULL DEFAULT uuid_generate_v4(), "action_type" "public"."moderator_actions_action_type_enum" NOT NULL, "action_reason" character varying(255) NOT NULL, "action_created_at" TIMESTAMP NOT NULL DEFAULT now(), "moderator_uuid" uuid NOT NULL, "report_uuid" uuid NOT NULL, "resource_uuid" uuid, "target_member_uuid" uuid, "comment_uuid" uuid, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_098eef9bb982a3c1a253c07994f" PRIMARY KEY ("uuid_moderation"))`);
        await queryRunner.query(`CREATE TABLE "formation_roles_roles" ("formationUuidFormation" uuid NOT NULL, "rolesUuidRole" character varying NOT NULL, CONSTRAINT "PK_638abb7f728f3bec94e34ac2846" PRIMARY KEY ("formationUuidFormation", "rolesUuidRole"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db21844676bf2fdea7ae839466" ON "formation_roles_roles" ("formationUuidFormation") `);
        await queryRunner.query(`CREATE INDEX "IDX_a818e9ef25ad57bb9db69fa70f" ON "formation_roles_roles" ("rolesUuidRole") `);
        await queryRunner.query(`CREATE TABLE "formation_channels_channels" ("formationUuidFormation" uuid NOT NULL, "channelsUuidChannel" character varying(19) NOT NULL, CONSTRAINT "PK_fb860ecdd17baf3abb7b7afb72e" PRIMARY KEY ("formationUuidFormation", "channelsUuidChannel"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cd7b54c64cfb08c1d730f623ae" ON "formation_channels_channels" ("formationUuidFormation") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffa1815b811112ec6b5cb48520" ON "formation_channels_channels" ("channelsUuidChannel") `);
        await queryRunner.query(`CREATE TABLE "promotions_followers" ("uuid_promotion" uuid NOT NULL, "uuid_member" uuid NOT NULL, CONSTRAINT "PK_52bcd4678cc03e4b0509e5f240e" PRIMARY KEY ("uuid_promotion", "uuid_member"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e626792cb72d82ceb028300297" ON "promotions_followers" ("uuid_promotion") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a0d5dc706787854d98091b43" ON "promotions_followers" ("uuid_member") `);
        await queryRunner.query(`CREATE TABLE "promotions_managers" ("uuid_promotion" uuid NOT NULL, "uuid_member" uuid NOT NULL, CONSTRAINT "PK_f9ffd4e467ee4358c27ee35110e" PRIMARY KEY ("uuid_promotion", "uuid_member"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c6292c3c603931a24647ddea7" ON "promotions_managers" ("uuid_promotion") `);
        await queryRunner.query(`CREATE INDEX "IDX_42092063ee0d0b82505e45d49b" ON "promotions_managers" ("uuid_member") `);
        await queryRunner.query(`CREATE TABLE "members_roles_roles" ("membersUuidMember" uuid NOT NULL, "rolesUuidRole" character varying NOT NULL, CONSTRAINT "PK_e33ff8fda888014e2d97422aa2d" PRIMARY KEY ("membersUuidMember", "rolesUuidRole"))`);
        await queryRunner.query(`CREATE INDEX "IDX_537b142cfdd9b542fe5148fb67" ON "members_roles_roles" ("membersUuidMember") `);
        await queryRunner.query(`CREATE INDEX "IDX_d17d482ec6a860c189d4ebedaf" ON "members_roles_roles" ("rolesUuidRole") `);
        await queryRunner.query(`ALTER TABLE "Campuses" ADD CONSTRAINT "FK_8ac2fd8957573e042f4fc8bdbd4" FOREIGN KEY ("uuid_guild") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Campuses" ADD CONSTRAINT "FK_82ea80834d8802c2f30e992425b" FOREIGN KEY ("uuid_role") REFERENCES "roles"("uuid_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Channels" ADD CONSTRAINT "FK_744cde7494385e835f276c0ae1a" FOREIGN KEY ("uuid_category") REFERENCES "categories"("uuid_category") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Channels" ADD CONSTRAINT "FK_134a855006978ae8524ab41b646" FOREIGN KEY ("uuid_guild") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guilds_templates" ADD CONSTRAINT "FK_f67fd100e0c22aa439a6c33b4e3" FOREIGN KEY ("uuidGuild") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guilds_templates" ADD CONSTRAINT "FK_5be5909b1bba191edc06f7c0ede" FOREIGN KEY ("uuid_category") REFERENCES "categories"("uuid_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_c03ee715facbb7b6a77f96a0aa6" FOREIGN KEY ("uuidGuild") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_2580e5895d8ab15865602745983" FOREIGN KEY ("uuid_guild_template") REFERENCES "guilds_templates"("uuid_guild_template") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_template" ADD CONSTRAINT "FK_5d695cb6ab42162c6c4eef2dce1" FOREIGN KEY ("formationUuidFormation") REFERENCES "formation"("uuidFormation") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formation" ADD CONSTRAINT "FK_61dc8c7b96d79d4d0a85b000929" FOREIGN KEY ("categoryUuid") REFERENCES "categories"("uuid_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formation" ADD CONSTRAINT "FK_0e33e64a89cd586968c3ab00523" FOREIGN KEY ("guildUuid") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_5ab23245a77ad3c6b28aaf79e04" FOREIGN KEY ("uuid_guild") REFERENCES "guilds"("uuid_guild") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Promotions" ADD CONSTRAINT "FK_b19be84223670a784cde8c0e3eb" FOREIGN KEY ("uuid_formation") REFERENCES "formation"("uuidFormation") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Promotions" ADD CONSTRAINT "FK_932ff715236b33caffac4e688eb" FOREIGN KEY ("uuid_guild") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Promotions" ADD CONSTRAINT "FK_dd8a497450643cd57b320413f6c" FOREIGN KEY ("uuid_role") REFERENCES "roles"("uuid_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Promotions" ADD CONSTRAINT "FK_04d8e2d4dbfb36a72110717a42a" FOREIGN KEY ("uuid_campus") REFERENCES "Campuses"("uuid_campus") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Promotions" ADD CONSTRAINT "FK_7f4379f872ac6471a39ed97a923" FOREIGN KEY ("uuid_category") REFERENCES "categories"("uuid_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members_informations" ADD CONSTRAINT "FK_c9c5d035e2236c8fc31b923e9c3" FOREIGN KEY ("uuidMember") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identification_requests" ADD CONSTRAINT "FK_199fe5af8e036ffedd4e8b39aac" FOREIGN KEY ("uuidMember") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboard_accounts" ADD CONSTRAINT "FK_e846d03e8221a331dbbb27e4ff6" FOREIGN KEY ("uuidDiscord") REFERENCES "discord_users"("uuid_discord") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_7d7156131815c6972860f7d0a55" FOREIGN KEY ("reporter_uuid") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_ffb1a33d4ce78a4c1b2a94b349f" FOREIGN KEY ("resource_uuid") REFERENCES "resources"("uuid_resource") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_580e454d47951f05d00d9e12e46" FOREIGN KEY ("reported_member_uuid") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_9fc142720afb4783af3e666fd2f" FOREIGN KEY ("uuid_member") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_b222ace54e4d1383ce261664417" FOREIGN KEY ("uuid_resource") REFERENCES "resources"("uuid_resource") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_ffc444d0753a67fd41be04082ac" FOREIGN KEY ("uuid_comment") REFERENCES "comments"("uuid_comment") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_6f97f8aea0898a6ae9cf2f65bf4" FOREIGN KEY ("uuid_member") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_3109f6a52da302b99b471c1696a" FOREIGN KEY ("uuid_resource") REFERENCES "resources"("uuid_resource") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resources" ADD CONSTRAINT "FK_0102ac2f78e69068c969ea22df9" FOREIGN KEY ("creator_uuid") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_d8ad7e9f368e3c012ca1c65d13e" FOREIGN KEY ("uuid_question") REFERENCES "questions"("uuid_question") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_28a0b29f6c406b8822d2eacefb8" FOREIGN KEY ("uuid_poll") REFERENCES "polls"("uuid_poll") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "polls" ADD CONSTRAINT "FK_e6c2ec286e77aaec1d9f482e177" FOREIGN KEY ("uuid_author") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_f9f107ecf5ef179942c61c21a74" FOREIGN KEY ("uuid_guild") REFERENCES "guilds"("uuid_guild") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_f749b4c11afb715c2f52ea6f7e4" FOREIGN KEY ("uuid_discord") REFERENCES "discord_users"("uuid_discord") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "xp_transactions" ADD CONSTRAINT "FK_04e889414bd0dc091f5ffc61f9c" FOREIGN KEY ("uuid_member") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer-templates" ADD CONSTRAINT "FK_422c7bf3eff978e915c797f54bc" FOREIGN KEY ("uuid_question_template") REFERENCES "question-templates"("uuid_question_template") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question-templates" ADD CONSTRAINT "FK_0a2d17649f34af1dc3ced78e463" FOREIGN KEY ("uuid_poll_template") REFERENCES "poll-templates"("uuid_poll_template") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" ADD CONSTRAINT "FK_f305c2c69e46b5158d88dc9faf7" FOREIGN KEY ("moderator_uuid") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" ADD CONSTRAINT "FK_477e373bb23c682b671accc78eb" FOREIGN KEY ("report_uuid") REFERENCES "reports"("uuid_report") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" ADD CONSTRAINT "FK_f64674062c037a4b11ceca96c3a" FOREIGN KEY ("resource_uuid") REFERENCES "resources"("uuid_resource") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" ADD CONSTRAINT "FK_20f947755e0141b9c5a621eae6a" FOREIGN KEY ("target_member_uuid") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" ADD CONSTRAINT "FK_3f335d85b6edf2b8a703b3084ee" FOREIGN KEY ("comment_uuid") REFERENCES "comments"("uuid_comment") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formation_roles_roles" ADD CONSTRAINT "FK_db21844676bf2fdea7ae8394667" FOREIGN KEY ("formationUuidFormation") REFERENCES "formation"("uuidFormation") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "formation_roles_roles" ADD CONSTRAINT "FK_a818e9ef25ad57bb9db69fa70f9" FOREIGN KEY ("rolesUuidRole") REFERENCES "roles"("uuid_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formation_channels_channels" ADD CONSTRAINT "FK_cd7b54c64cfb08c1d730f623ae2" FOREIGN KEY ("formationUuidFormation") REFERENCES "formation"("uuidFormation") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "formation_channels_channels" ADD CONSTRAINT "FK_ffa1815b811112ec6b5cb485203" FOREIGN KEY ("channelsUuidChannel") REFERENCES "Channels"("uuid_channel") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "promotions_followers" ADD CONSTRAINT "FK_e626792cb72d82ceb0283002979" FOREIGN KEY ("uuid_promotion") REFERENCES "Promotions"("uuid_promotion") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "promotions_followers" ADD CONSTRAINT "FK_e3a0d5dc706787854d98091b43a" FOREIGN KEY ("uuid_member") REFERENCES "members"("uuid_member") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions_managers" ADD CONSTRAINT "FK_8c6292c3c603931a24647ddea74" FOREIGN KEY ("uuid_promotion") REFERENCES "Promotions"("uuid_promotion") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "promotions_managers" ADD CONSTRAINT "FK_42092063ee0d0b82505e45d49ba" FOREIGN KEY ("uuid_member") REFERENCES "members"("uuid_member") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "members_roles_roles" ADD CONSTRAINT "FK_537b142cfdd9b542fe5148fb67f" FOREIGN KEY ("membersUuidMember") REFERENCES "members"("uuid_member") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "members_roles_roles" ADD CONSTRAINT "FK_d17d482ec6a860c189d4ebedafb" FOREIGN KEY ("rolesUuidRole") REFERENCES "roles"("uuid_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "members_roles_roles" DROP CONSTRAINT "FK_d17d482ec6a860c189d4ebedafb"`);
        await queryRunner.query(`ALTER TABLE "members_roles_roles" DROP CONSTRAINT "FK_537b142cfdd9b542fe5148fb67f"`);
        await queryRunner.query(`ALTER TABLE "promotions_managers" DROP CONSTRAINT "FK_42092063ee0d0b82505e45d49ba"`);
        await queryRunner.query(`ALTER TABLE "promotions_managers" DROP CONSTRAINT "FK_8c6292c3c603931a24647ddea74"`);
        await queryRunner.query(`ALTER TABLE "promotions_followers" DROP CONSTRAINT "FK_e3a0d5dc706787854d98091b43a"`);
        await queryRunner.query(`ALTER TABLE "promotions_followers" DROP CONSTRAINT "FK_e626792cb72d82ceb0283002979"`);
        await queryRunner.query(`ALTER TABLE "formation_channels_channels" DROP CONSTRAINT "FK_ffa1815b811112ec6b5cb485203"`);
        await queryRunner.query(`ALTER TABLE "formation_channels_channels" DROP CONSTRAINT "FK_cd7b54c64cfb08c1d730f623ae2"`);
        await queryRunner.query(`ALTER TABLE "formation_roles_roles" DROP CONSTRAINT "FK_a818e9ef25ad57bb9db69fa70f9"`);
        await queryRunner.query(`ALTER TABLE "formation_roles_roles" DROP CONSTRAINT "FK_db21844676bf2fdea7ae8394667"`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" DROP CONSTRAINT "FK_3f335d85b6edf2b8a703b3084ee"`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" DROP CONSTRAINT "FK_20f947755e0141b9c5a621eae6a"`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" DROP CONSTRAINT "FK_f64674062c037a4b11ceca96c3a"`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" DROP CONSTRAINT "FK_477e373bb23c682b671accc78eb"`);
        await queryRunner.query(`ALTER TABLE "moderator_actions" DROP CONSTRAINT "FK_f305c2c69e46b5158d88dc9faf7"`);
        await queryRunner.query(`ALTER TABLE "question-templates" DROP CONSTRAINT "FK_0a2d17649f34af1dc3ced78e463"`);
        await queryRunner.query(`ALTER TABLE "answer-templates" DROP CONSTRAINT "FK_422c7bf3eff978e915c797f54bc"`);
        await queryRunner.query(`ALTER TABLE "xp_transactions" DROP CONSTRAINT "FK_04e889414bd0dc091f5ffc61f9c"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_f749b4c11afb715c2f52ea6f7e4"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_f9f107ecf5ef179942c61c21a74"`);
        await queryRunner.query(`ALTER TABLE "polls" DROP CONSTRAINT "FK_e6c2ec286e77aaec1d9f482e177"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_28a0b29f6c406b8822d2eacefb8"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_d8ad7e9f368e3c012ca1c65d13e"`);
        await queryRunner.query(`ALTER TABLE "resources" DROP CONSTRAINT "FK_0102ac2f78e69068c969ea22df9"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_3109f6a52da302b99b471c1696a"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_6f97f8aea0898a6ae9cf2f65bf4"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_ffc444d0753a67fd41be04082ac"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_b222ace54e4d1383ce261664417"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_9fc142720afb4783af3e666fd2f"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_580e454d47951f05d00d9e12e46"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_ffb1a33d4ce78a4c1b2a94b349f"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_7d7156131815c6972860f7d0a55"`);
        await queryRunner.query(`ALTER TABLE "dashboard_accounts" DROP CONSTRAINT "FK_e846d03e8221a331dbbb27e4ff6"`);
        await queryRunner.query(`ALTER TABLE "identification_requests" DROP CONSTRAINT "FK_199fe5af8e036ffedd4e8b39aac"`);
        await queryRunner.query(`ALTER TABLE "members_informations" DROP CONSTRAINT "FK_c9c5d035e2236c8fc31b923e9c3"`);
        await queryRunner.query(`ALTER TABLE "Promotions" DROP CONSTRAINT "FK_7f4379f872ac6471a39ed97a923"`);
        await queryRunner.query(`ALTER TABLE "Promotions" DROP CONSTRAINT "FK_04d8e2d4dbfb36a72110717a42a"`);
        await queryRunner.query(`ALTER TABLE "Promotions" DROP CONSTRAINT "FK_dd8a497450643cd57b320413f6c"`);
        await queryRunner.query(`ALTER TABLE "Promotions" DROP CONSTRAINT "FK_932ff715236b33caffac4e688eb"`);
        await queryRunner.query(`ALTER TABLE "Promotions" DROP CONSTRAINT "FK_b19be84223670a784cde8c0e3eb"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_5ab23245a77ad3c6b28aaf79e04"`);
        await queryRunner.query(`ALTER TABLE "formation" DROP CONSTRAINT "FK_0e33e64a89cd586968c3ab00523"`);
        await queryRunner.query(`ALTER TABLE "formation" DROP CONSTRAINT "FK_61dc8c7b96d79d4d0a85b000929"`);
        await queryRunner.query(`ALTER TABLE "thread_template" DROP CONSTRAINT "FK_5d695cb6ab42162c6c4eef2dce1"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_2580e5895d8ab15865602745983"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_c03ee715facbb7b6a77f96a0aa6"`);
        await queryRunner.query(`ALTER TABLE "guilds_templates" DROP CONSTRAINT "FK_5be5909b1bba191edc06f7c0ede"`);
        await queryRunner.query(`ALTER TABLE "guilds_templates" DROP CONSTRAINT "FK_f67fd100e0c22aa439a6c33b4e3"`);
        await queryRunner.query(`ALTER TABLE "Channels" DROP CONSTRAINT "FK_134a855006978ae8524ab41b646"`);
        await queryRunner.query(`ALTER TABLE "Channels" DROP CONSTRAINT "FK_744cde7494385e835f276c0ae1a"`);
        await queryRunner.query(`ALTER TABLE "Campuses" DROP CONSTRAINT "FK_82ea80834d8802c2f30e992425b"`);
        await queryRunner.query(`ALTER TABLE "Campuses" DROP CONSTRAINT "FK_8ac2fd8957573e042f4fc8bdbd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d17d482ec6a860c189d4ebedaf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_537b142cfdd9b542fe5148fb67"`);
        await queryRunner.query(`DROP TABLE "members_roles_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42092063ee0d0b82505e45d49b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c6292c3c603931a24647ddea7"`);
        await queryRunner.query(`DROP TABLE "promotions_managers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a0d5dc706787854d98091b43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e626792cb72d82ceb028300297"`);
        await queryRunner.query(`DROP TABLE "promotions_followers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffa1815b811112ec6b5cb48520"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd7b54c64cfb08c1d730f623ae"`);
        await queryRunner.query(`DROP TABLE "formation_channels_channels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a818e9ef25ad57bb9db69fa70f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db21844676bf2fdea7ae839466"`);
        await queryRunner.query(`DROP TABLE "formation_roles_roles"`);
        await queryRunner.query(`DROP TABLE "moderator_actions"`);
        await queryRunner.query(`DROP TYPE "public"."moderator_actions_action_type_enum"`);
        await queryRunner.query(`DROP TABLE "question-templates"`);
        await queryRunner.query(`DROP TABLE "answer-templates"`);
        await queryRunner.query(`DROP TABLE "poll-templates"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "xp_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."xp_transactions_reference_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."xp_transactions_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."xp_transactions_transaction_type_enum"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP TABLE "polls"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TABLE "answers"`);
        await queryRunner.query(`DROP TABLE "resources"`);
        await queryRunner.query(`DROP TYPE "public"."resources_status_enum"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "votes"`);
        await queryRunner.query(`DROP TYPE "public"."votes_type_enum"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP TABLE "discord_users"`);
        await queryRunner.query(`DROP TABLE "dashboard_accounts"`);
        await queryRunner.query(`DROP TABLE "identification_requests"`);
        await queryRunner.query(`DROP TABLE "members_informations"`);
        await queryRunner.query(`DROP TABLE "guilds"`);
        await queryRunner.query(`DROP TABLE "Promotions"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "formation"`);
        await queryRunner.query(`DROP TABLE "thread_template"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "guilds_templates"`);
        await queryRunner.query(`DROP TABLE "Channels"`);
        await queryRunner.query(`DROP TABLE "Campuses"`);
    }

}
